//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos.Infraestructure
{
    using System;
    using System.Collections.Generic;
    
    public partial class LibrosUnidade
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LibrosUnidade()
        {
            this.Ventas = new HashSet<Venta>();
        }
    
        public int idLibroUnidades { get; set; }
        public int idLibro { get; set; }
        public int idUbicacion { get; set; }
        public string codigo { get; set; }
        public Nullable<bool> Estado { get; set; }
    
        public virtual Libro Libro { get; set; }
        public virtual Ubicacione Ubicacione { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Venta> Ventas { get; set; }
    }
}
