//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos.Infraestructure
{
    using System;
    using System.Collections.Generic;
    
    public partial class Venta
    {
        public int idVenta { get; set; }
        public int idLibroUnidades { get; set; }
        public System.DateTime fechaVenta { get; set; }
        public string nombreCliente { get; set; }
        public decimal precio { get; set; }
    
        public virtual LibrosUnidade LibrosUnidade { get; set; }
    }
}
